apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.services.backend.port }}
      targetPort: 8000
  type: {{ .Values.services.backend.type }}
