apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.services.frontend.port }}
      targetPort: 5173
      nodePort: {{ .Values.services.frontend.nodePort }}
  type: {{ .Values.services.frontend.type }}
