apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.services.redis.port }}
      targetPort: 6379
  type: {{ .Values.services.redis.type }}
